### ISSUE TITLE
Integration Guide

### ISSUE THREAD

**Issue by solomonshalom** [fuma-nama/fuma-comment#20]
Hi!

I am curious to know on how to integrate this into an existing app?

Would love to know!

Thanks!

**Comment by fuma-nama** [comment]
https://fuma-comment.vercel.app/docs

**Comment by solomonshalom** [comment]
> https://fuma-comment.vercel.app/docs
> 
> Keep in mind it's still in development, there can be breaking changes until we reached 1.0

I see! Got it - small suggestion, have firebase as an integration option as well :D

**Comment by fuma-nama** [comment]
I'm too busy tho, welcome to submit a PR to help with the development ;)
