### ISSUE TITLE
[Question] How the comment system will be used in Fumadocs

### ISSUE THREAD

**Issue by shenxiangzhuang** [fuma-nama/fuma-comment#37]
Hi, I'm using fumadocs for docs in my website, which works well(thank you for your work!) and I'm wondering how can I integrate this comment system into fumadocs?  Will this need some other infrastructures(databases for example)?

Hope the comment system doesn't need any infras(like Giscus) and can be easily integrate into fumadocs!

**Comment by fuma-nama** [comment]
The comment system persists comments with databases, so you will need a database. I'll see if it's possible to integrate with GitHub directly but you will need a database for now.

**Comment by shenxiangzhuang** [comment]
OK. Thanks for your timely reply!
